services:
  # DB (MariaDB)
  talent-bridge-db:
    image: mariadb:latest
    container_name: talent-bridge-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ../mysql_dataa:/var/lib/mysql
    networks:
      - tb_network

  # REDIS
  redis:
    image: redis:alpine
    container_name: talent-bridge-redis
    ports:
      - "6379:6379"
    networks:
      - tb_network

  # AUTH SERVICE
  auth_service:
    build:
      context: ..
      dockerfile: service/auth_service/Dockerfile
    container_name: tb_auth_service
    ports:
      - "8000:8000"
    volumes:
      - ../..:/app
    environment:
      PYTHONPATH: ${PYTHONPATH}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - talent-bridge-db
    networks:
      - tb_network

  # CORE SERVICE
  core_service:
    build:
      context: ..
      dockerfile: service/core_service/Dockerfile
    container_name: tb_core_service
    ports:
      - "8001:8001"
    volumes:
      - ../..:/app
    environment:
      PYTHONPATH: ${PYTHONPATH}
      DATABASE_URL: ${DATABASE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    depends_on:
      - talent-bridge-db
      - redis
    networks:
      - tb_network

  # ANALYSIS WORKER
  analysis_worker:
    build:
      context: ..
      dockerfile: service/analysis_worker/Dockerfile
    # fara container_name fix, ca sa putem rula mai multe instante (scale)
    deploy:
      replicas: 3
    volumes:
      - ../..:/app
      - ./analysis_worker/app/data:/app/service/analysis_worker/app/data
    environment:
      PYTHONPATH: ${PYTHONPATH}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - redis
      - talent-bridge-db
    networks:
      - tb_network

networks:
  tb_network:
    driver: bridge