version: '3.8'

services:
  #DB (MariaDB)
  talent-bridge-db:
    image: mariadb:latest
    container_name: talent-bridge-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rares545
      MYSQL_DATABASE: db_talentbridge
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - tb_network

  #REDIS
  redis:
    image: redis:alpine
    container_name: talent-bridge-redis
    ports:
      - "6379:6379"
    networks:
      - tb_network

  #AUTH SERVICE
  auth_service:
    build:
      context: ..
      dockerfile: service/auth_service/Dockerfile
    container_name: tb_auth_service
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    depends_on:
      - talent-bridge-db
    environment:
      DATABASE_URL: mysql+pymysql://root:Rares545@talent-bridge-db/db_talentbridge
    networks:
      - tb_network

  #CORE SERVICE
  core_service:
    build:
      context: ..
      dockerfile: service/core_service/Dockerfile
    container_name: tb_core_service
    ports:
      - "8001:8001"
    volumes:
      - ..:/app
    depends_on:
      - talent-bridge-db
    environment:
      DATABASE_URL: mysql+pymysql://root:Rares545@talent-bridge-db/db_talentbridge
      CELERY_BROKER_URL: redis://talent-bridge-redis:6379/0
      CELERY_RESULT_BACKEND: redis://talent-bridge-redis:6379/0
    networks:
      - tb_network

  #ANALYSIS WORKER (Celery)
  analysis_worker:
    build:
      context: ..
      dockerfile: service/analysis_worker/Dockerfile
    container_name: tb_analysis_worker
    volumes:
      - ..:/app
    depends_on:
      - redis
      - talent-bridge-db
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DATABASE_URL: mysql+pymysql://root:Rares545@talent-bridge-db/db_talentbridge
    networks:
      - tb_network

networks:
  tb_network:
    driver: bridge